strategies:
  safe:
    theirs:
      - '**/*lock*.json'
      - '**/pnpm-lock.yaml'
      - '**/yarn.lock'
      - 'package-lock.json'
      - '**/*.md'
      - '.github/**'
    ours:
      - '**/.env.example'
  json:
    theirs:
      - '**/*lock*.json'
      - '**/pnpm-lock.yaml'
      - '**/yarn.lock'
      - 'package-lock.json'
      - '**/package.json'
      - '**/tsconfig.json'
      - '**/.eslintrc.json'
      - '**/vercel.json'
      - '**/railway.json'
      - '**/*.json'