
# Texas Data Sources Registry - Updated for TX Permits Integration
# Focused on Dallas, Austin, Arlington with proper field aliases

metadata:
  state: "TX"
  coverage_version: "1.1.0"
  last_updated: "2024-12-19"
  tier_1_definition: "Primary cities with real-time API access"

# Primary Sources for TX Permits Integration
sources:
  # Dallas - Building Permits (Socrata)
  - id: dallas_permits
    kind: socrata
    domain: dallasopendata.com
    dataset: e7gq-4sah
    entity: permits
    updated_field: last_update_date|issued_date|file_date
    primary_key: permit_number|application_number|record_id
    cadence: daily
    license: public
    provenance_url: https://www.dallasopendata.com/dataset/e7gq-4sah
    jurisdiction: Dallas
    city: Dallas
    county: Dallas

  # Austin - Building Permits (Socrata)
  - id: austin_permits
    kind: socrata
    domain: data.austintexas.gov
    dataset: 3syk-w9eu
    entity: permits
    updated_field: last_update|issued_date|applied_date
    primary_key: permit_num|record_id|application_number
    cadence: daily
    license: public
    provenance_url: https://data.austintexas.gov/d/3syk-w9eu
    jurisdiction: Austin
    city: Austin
    county: Travis

  # Arlington - Building Permits (ArcGIS)
  - id: arlington_permits
    kind: arcgis
    base_url: https://gis2.arlingtontx.gov/agsext2/rest/services/OpenData/OD_Property/MapServer
    layer: 1
    entity: permits
    updated_field: EditDate|IssueDate|AppliedDate
    primary_key: OBJECTID|PermitNum|RecordID
    cadence: daily
    license: public
    provenance_url: https://gis2.arlingtontx.gov/open-data
    jurisdiction: Arlington
    city: Arlington
    county: Tarrant

  # Houston - TPIA Placeholder (CSV import)
  - id: "tx-houston-permits"
    name: "Houston Building Permits"
    kind: "tpia"
    endpoint: "manual_delivery"
    updated_field: "issue_date"
    primary_key: "permit_number"
    cadence: "monthly"
    entity: "permits"
    license: "public_information"
    provenance_url: "https://www.houstontx.gov/planning/DevelopReview/"

  # Harris County - Permits (ArcGIS, backward compatibility)
  - id: "tx-harris-county"
    name: "Harris County Building Permits"
    kind: "arcgis"
    endpoint: "https://www.gis.hctx.net/arcgishcpid/rest/services/Permits/IssuedPermits/FeatureServer/0"
    updated_field: "ISSUEDDATE"
    primary_key: "PERMITNUMBER"
    cadence: "daily"
    entity: "permits"
    license: "public_domain"
    provenance_url: "https://hcad.org"

# Rate limiting and pagination settings
rate_limits:
  arcgis: 5  # requests per second
  socrata: 5  # requests per second
  csv_http: 2  # requests per second
  tpia: 0  # manual processing

pagination:
  arcgis:
    method: "offset"
    page_size: 1000
  socrata:
    method: "offset"
    page_size: 1000
  csv_http:
    method: "date_range"
    page_size: 500

# Legacy environment variable backward compatibility
# Houston permits will still work with HC_ISSUED_PERMITS_URL if set
backward_compatibility:
  HC_ISSUED_PERMITS_URL: "tx-harris-county"

