
# Texas Data Sources Registry - City-First APIs with TPIA placeholders
# Initial focus: Dallas Socrata, Austin Socrata/Tyler, Arlington ArcGIS, Houston (TPIA/CSV)

metadata:
  state: "TX"
  coverage_version: "1.0.0"
  last_updated: "2024-12-19"
  tier_1_definition: "Population > 100K or high permit volume (>1K permits/year)"

# Primary Sources (Daily Ingestion)
sources:
  # Dallas - Building Permits (Socrata)
  - id: "tx-dallas-permits"
    name: "Dallas Building Permits"
    kind: "socrata"
    endpoint: "https://www.dallasopendata.com/resource/e7gq-4sah.json"
    updated_field: "issued_date"
    primary_key: "permit_number"
    cadence: "daily"
    entity: "permits"
    license: "open_data"
    provenance_url: "https://www.dallasopendata.com/City-Services/Building-Permits/e7gq-4sah"

  # Austin - Building Permits (Socrata/Tyler)
  - id: "tx-austin-permits"
    name: "Austin Building Permits"
    kind: "socrata"
    endpoint: "https://data.austintexas.gov/resource/3syk-w9eu.json"
    updated_field: "issued_date"
    primary_key: "permit_number"
    cadence: "daily"
    entity: "permits"
    license: "open_data"
    provenance_url: "https://data.austintexas.gov/Building-and-Development/Issued-Construction-Permits/3syk-w9eu"

  # Arlington - Building Permits (ArcGIS)
  - id: "tx-arlington-permits"
    name: "Arlington Building Permits"
    kind: "arcgis"
    endpoint: "https://gis.arlingtontx.gov/arcgis/rest/services/Permits/FeatureServer/0"
    updated_field: "ISSUE_DATE"
    primary_key: "PERMIT_ID"
    cadence: "daily"
    entity: "permits"
    license: "public_domain"
    provenance_url: "https://gis.arlingtontx.gov/portal/home/item.html?id=permits"

  # Houston - TPIA Placeholder (CSV import)
  - id: "tx-houston-permits"
    name: "Houston Building Permits"
    kind: "tpia"
    endpoint: "manual_delivery"
    updated_field: "issue_date"
    primary_key: "permit_number"
    cadence: "monthly"
    entity: "permits"
    license: "public_information"
    provenance_url: "https://www.houstontx.gov/planning/DevelopReview/"

  # Harris County - Permits (ArcGIS, backward compatibility)
  - id: "tx-harris-county"
    name: "Harris County Building Permits"
    kind: "arcgis"
    endpoint: "https://www.gis.hctx.net/arcgishcpid/rest/services/Permits/IssuedPermits/FeatureServer/0"
    updated_field: "ISSUEDDATE"
    primary_key: "PERMITNUMBER"
    cadence: "daily"
    entity: "permits"
    license: "public_domain"
    provenance_url: "https://hcad.org"

# Rate limiting and pagination settings
rate_limits:
  arcgis: 5  # requests per second
  socrata: 5  # requests per second
  csv_http: 2  # requests per second
  tpia: 0  # manual processing

pagination:
  arcgis:
    method: "offset"
    page_size: 1000
  socrata:
    method: "offset"
    page_size: 1000
  csv_http:
    method: "date_range"
    page_size: 500

# Legacy environment variable backward compatibility
# Houston permits will still work with HC_ISSUED_PERMITS_URL if set
backward_compatibility:
  HC_ISSUED_PERMITS_URL: "tx-harris-county"

