name: Agents Pipeline
on:
  workflow_dispatch:
    inputs:
      file:
        description: "Input file path (XLS/XLSX/CSV/HTML) in repo"
        required: true
      source:
        description: "Source name (e.g., city_of_houston_xlsx)"
        default: "custom_source"

jobs:
  run:
    runs-on: [self-hosted, linux, x64, scrape]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11', cache: 'pip' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-agents.txt

      - name: Ensure dirs
        run: mkdir -p artifacts/parsed

      - name: Parse → NDJSON
        run: |
          python scripts/agents/parse_unstructured.py "${{ github.event.inputs.file }}" "${{ github.event.inputs.source }}" > artifacts/parsed/source.ndjson

      - name: Normalize
        run: |
          python scripts/agents/normalize_addresses.py < artifacts/parsed/source.ndjson > artifacts/normalized.ndjson

      - name: Geocode + county
        run: |
          python scripts/agents/geocode_county.py < artifacts/normalized.ndjson > artifacts/geocoded.ndjson

      - name: Dedupe
        run: |
          python scripts/agents/dedupe_records.py < artifacts/geocoded.ndjson > artifacts/final.ndjson

      - name: Upsert Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python scripts/agents/upsert_supabase.py artifacts/final.ndjson

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agents-output-${{ github.run_id }}
          path: artifacts/**
          if-no-files-found: warn