name: AI Auto-PR Receiver

on:
  # Listen for repository dispatch events with specific event type
  repository_dispatch:
    types: [ai_autopr_request]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  ai-autopr-receiver:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set token variable
        run: |
          # Set token using shell logic instead of logical OR
          TOKEN="${{ secrets.GITHUB_TOKEN_BOT }}"
          [ -z "$TOKEN" ] && TOKEN="${{ secrets.GITHUB_TOKEN }}"
          echo "CHECKOUT_TOKEN=$TOKEN" >> $GITHUB_ENV
          
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ env.CHECKOUT_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup GitHub CLI
        run: |
          # GitHub CLI should be pre-installed on ubuntu-latest
          gh --version

      - name: Extract instruction from repository dispatch payload
        id: extract_instruction
        run: |
          INSTRUCTION="${{ github.event.client_payload.instruction }}"
          echo "instruction=$INSTRUCTION" >> $GITHUB_OUTPUT
          echo "Found instruction: $INSTRUCTION"
          
          if [ -z "$INSTRUCTION" ]; then
            echo "ERROR: No instruction found in client_payload.instruction"
            exit 1
          fi

      - name: Run AI Auto-PR script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          INSTRUCTION: ${{ steps.extract_instruction.outputs.instruction }}
        run: |
          # Set token using shell logic instead of logical OR
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN_BOT }}"
          [ -z "$GITHUB_TOKEN" ] && GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          export GITHUB_TOKEN
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "ERROR: OPENAI_API_KEY secret is required but not set"
            exit 1
          fi
          
          if [ -z "$INSTRUCTION" ]; then
            echo "ERROR: No instruction found in repository dispatch payload"
            exit 1
          fi
          
          echo "Running AI Auto-PR receiver with instruction: $INSTRUCTION"
          echo "Event type: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          
          chmod +x scripts/ai-autopr.js
          node scripts/ai-autopr.js