name: PR CI
on:
  pull_request:
    branches: [main]
permissions:
  contents: write
  pull-requests: write
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
          cache: 'npm'
      - name: Root install (no build)
        run: npm ci
      - name: Verify single React source and same major
        run: node scripts/check-react-mismatch.mjs
      - name: Build frontend
        run: cd frontend && npm ci && npm run build
      - name: Env schema check (local)
        run: node scripts/check-required-env.mjs
