name: DB Migrations
"on":
  pull_request:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
      - name: Apply migrations (diff on PR, push on main)
        env:
          # postgres connection string (service role)
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          set -Eeuo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Running database diff for pull request..."
            supabase db diff --db-url "$SUPABASE_DB_URL"
          else
            echo "Pushing database changes to main branch..."
            supabase db push --db-url "$SUPABASE_DB_URL"
          fi
