name: DB Migrations
on:
  pull_request:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: supabase/setup-cli@v1
      - name: Debug env
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "PROJECT_REF: $PROJECT_REF"
          echo "SUPABASE_ACCESS_TOKEN: ${#SUPABASE_ACCESS_TOKEN} characters"
          echo "DB_PASSWORD: ${#DB_PASSWORD} characters"
      - name: Link and apply migrations (diff on PR, push on main)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          set -Eeuo pipefail
          
          # Link to Supabase project
          supabase link --project-ref "$PROJECT_REF"
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Running database diff for pull request..."
            supabase db diff
          else
            echo "Pushing database changes to main branch..."
            supabase db push
          fi
