name: Supabase DB

on:
  pull_request:
  push:
    branches: [main]

jobs:
  db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          PROJECT_REF:           ${{ secrets.PROJECT_REF }}
        run: |
          set -euo pipefail
          supabase link --project-ref "$PROJECT_REF"

      # Optional: if you prefer DATABASE_URL instead of DB_PASSWORD, skip this step
      - name: Build DB URL from DB_PASSWORD
        if: ${{ secrets.DATABASE_URL == '' }}
        env:
          PROJECT_REF: ${{ secrets.PROJECT_REF }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@db.${PROJECT_REF}.supabase.co:5432/postgres" >> $GITHUB_ENV

      - name: PRs => show diff, Main => push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL != '' && secrets.DATABASE_URL || env.DATABASE_URL }}
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Running database diff for PR..."
            supabase db diff --db-url "$DATABASE_URL"
          else
            echo "Pushing database changes to main..."
            supabase db push --db-url "$DATABASE_URL"
          fi