name: Secrets & Endpoint Auditor
on:
  schedule: [{ cron: "0 9 * * 1" }]
  workflow_dispatch: {}

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets exist
        env:
          S1: ${{ secrets.SUPABASE_URL }}
          S2: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          S3: ${{ secrets.HC_ISSUED_PERMITS_URL }}
          S4: ${{ secrets.DALLAS_PERMITS_URL }}
        run: |
          ok=1
          for v in S1 S2 S3 S4; do [ -z "${!v}" ] && echo "::error ::Missing $v" && ok=0; done
          [ $ok -eq 1 ]
      - name: Probe Supabase REST
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Prefer: count=exact, head=true" \
            "$SUPABASE_URL/rest/v1/leads?select=id&limit=1")
          echo "Supabase HTTP=$code"; [ "$code" = "200" ] || [ "$code" = "206" ]
      - name: Probe sources (HEAD)
        env:
          H: ${{ secrets.HC_ISSUED_PERMITS_URL }}
          D: ${{ secrets.DALLAS_PERMITS_URL }}
        run: |
          for u in "$H" "$D"; do [ -z "$u" ] && continue; curl -fsSI "$u" >/dev/null || exit 1; done